### ISSUE TITLE
Feature Request: Function parameter expansion support

### ISSUE THREAD

**Issue by butterflyfish** [ncm2/ncm2-tagprefix#1]
ctags file have function prototype. It's fantastic if ncm2-tagprefix support function parameter expansion like ncm2-pyclang.

Not all c/c++ project can use ncm2-pyclang. Some private projects written for embedded(cross compile) device, GCC is only choice.

**Comment by roxma** [comment]
> Some private projects written for embedded(cross compile) device, GCC is only choice.

I use gcc too.

Clang is only for completion for my project. It should work as long as you setup the compile options.

Clang is designed to be a gcc alternative, Their options are mostly compatible.

I'm not interested in adding this support for tag source.

**Comment by butterflyfish** [comment]
thank you for your feedback.
