### ISSUE TITLE
Option to remove file path from the tag autocompletion

### ISSUE THREAD

**Issue by kristijanhusak** [ncm2/ncm2-tagprefix#2]
Hi,

is there a way to remove the file path of the autocompleted tag? If not, can it be added somehow? It can give some falsy results, and it extends the width of the autocompletion a lot, without any real purpose. Here's example screenshot:

![screenshot](https://i.imgur.com/2aU0Ok5.png)

It shows that it comes from tests, because there are multiple definitions of TaxRepository in the tags, and the tests one is the last.

**Comment by roxma** [comment]
Current implementation respect the `:tagfiles()` results.

```vim
func! ncm2_tagprefix#on_complete(ctx)
    call g:ncm2_tagprefix#proc.try_notify('on_complete', a:ctx, getcwd(), tagfiles())
endfunc
```

You should probably configure the `:help 'tags'` option.

**Comment by kristijanhusak** [comment]
I'm not exactly sure what can i do with the tags here? You mean set up the sorting so i get the proper file path, or there's way to hide file path? I don't see anything in help for that.

**Comment by roxma** [comment]
Maybe I have misunderstood your description.

Do you mean you want to show the `TaxRepository` in the popup menu only?

**Comment by kristijanhusak** [comment]
Yes, i want to see only `TaxRepository [#]`.

**Comment by roxma** [comment]
You could write a filter to empty the `menu` field of the `matches`

A filter implementation example: https://github.com/ncm2/ncm2/blob/master/pythonx/ncm2_filter/same_word.py

Place the file into the  `{rtp}/pythonx/ncm2_filter/` directory, the change the ncm2-tagprefix config to apply the filter:

`let g:ncm2_tagprefix#source = {'filter': "no_menu"}`

**Comment by kristijanhusak** [comment]
Ok, thanks!
