### ISSUE TITLE
Why does this only support prefix match?

### ISSUE THREAD

**Issue by alok** [ncm2/ncm2-tagprefix#6]

**Comment by roxma** [comment]
This plugin uses binary search instead of scanning the whole tag file.

**Comment by caneta** [comment]
Is this plugin the only way, if I use [vim-gutentags](https://github.com/ludovicchabant/vim-gutentags) instead of [gen_tags.vim](https://github.com/jsfaint/gen_tags.vim)/[ncm2-gtags](https://github.com/ncm2/ncm2-gtags)?
